### ISSUE TITLE
bug in print stylesheet?

### ISSUE THREAD

**Issue by holfordm** [bodleian/medieval-mss#170]
When printing a record, the bottom of the first page contains the website footer (accessibility ... contact us) which can print on top of part of the record, making a small part of it illegible. Is this one for @IgnatG ?

**Comment by IgnatG** [comment]
yup. I'll have a look

**Comment by andrew-morrison** [comment]
QA is now updated. It seems to have worked, for me, in Firefox and Chrome. I'll push it to production with other changes soon.

@IgnatG: Are you going to apply this fix to the other TEI catalogues?

**Comment by IgnatG** [comment]
Yup - I'll apply it to the others as well!

**Comment by IgnatG** [comment]
//ready now

**Comment by andrew-morrison** [comment]
I have updated the QA sites of all TEI catalogues (except Armenian and South Asian). Let me know when I can go ahead and push the same change to the production web sites.

**Comment by IgnatG** [comment]
wait for my green-light. I want to update something else on it.

**Comment by IgnatG** [comment]
done now - I hope. It would require another update though. Start with QA first, please

**Comment by andrew-morrison** [comment]
All TEI catalogue QA sites now redeployed.

The result is fewer pages when printing, in a smaller and serif font.

Also anything which is a link has the href printed afterwards in brackets. That is useful for external links but for internal ones that is something like /catalog/person_1234, which makes reading a typical msItem pretty difficult:

>  Gregory of Nazianzus (/catalog/person_108675755) , Homilies (/catalog/work_1846) ,
with scholia by Maximus Confessor (/catalog/person_106970843) , Basil of Caesarea the younger (/catalog/person_261109502) , and Georgius Mocenus (/catalog/person_400527)

The same applies to all the links on work/person/place pages which, with all the new information we're adding to them, users will be more likely to want to print.

**Comment by IgnatG** [comment]
I will leave this as a question for @holfordm:
a) Would you find useful to see where the links are pointing to when you print the page? 
> i.e. Gregory of Nazianzus (/catalog/person_108675755)

b) Or  Would you rather see the text only?
> i.e. Gregory of Nazianzus

**Comment by holfordm** [comment]
text only please!
If possible I would also prefer a larger font and for the headings (Physical Description, History etc.) to be larger.

**Comment by IgnatG** [comment]
//done - re-open if needed

**Comment by holfordm** [comment]
It's still not perfect -- the main headings (Contents, Physical Description, History etc.) are still too small, and in multi part manuscripts the heading for each part is also too small. Not urgent gripes, but worth checking if the other catalogues are happy with it, if not we should reopen.

**Comment by IgnatG** [comment]
can I get some links to see them as examples, please?

**Comment by IgnatG** [comment]
done

**Comment by andrew-morrison** [comment]
Re-depolying to QA now.

**Comment by andrew-morrison** [comment]
Done. @holfordm: Please take another look.
